name: build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: NPM Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          path: | 
            ~/.npm
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Download node modules
        run: npm install
      - name: Build App
        run: npm run build:prod
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
